### ISSUE TITLE
blue tick

### ISSUE THREAD

**Issue by muhammadumar313** [Automattic/gravatar#111]
/op![Image](https://github.com/user-attachments/assets/28df51e3-7763-426e-897d-ee0c90d54681)
![Image](https://github.com/user-attachments/assets/7418ba29-394f-4c4e-a52c-6ae5f0218ec6)
# Feature Request

## Description / Use Case

Describe the feature you'd like to see added. Include the potential use case(s) to help us understand its impact.

## Proposed Solution

Have an idea on how to implement this feature? Please share your thoughts or possible approaches.

## Alternatives

Did you consider any alternative solutions or features? Kindly share that information as it helps in thorough understanding and evaluation.

## Additional Information

Feel free to add any other context, like screenshots, examples, or additional comments that could help us understand your feature request better.

**Comment by muhammadumar313** [comment]
[![Image](https://github.com/user-attachments/assets/605c38e6-bbba-45dd-8c83-34c5a8ac23ec)
`](url)`

**Comment by aaronfc** [comment]
Hey @muhammadumar313 , thanks for your interes. Can you elaborate a bit more on what you are suggesting?

Please, try to fill the template with the required information.

If there isn't any further explanation I will close the ticket in the next few days.
