### ISSUE TITLE
Wrong Avatar under Retro

### ISSUE THREAD

**Issue by kresch23** [Automattic/gravatar#15]
Hello together

I noticed that one of our users got an avatar with a human picture. Retro is selected in the settings and the picture below appears.

https://secure.gravatar.com/avatar/667992afa821dd5b31def027c949aee1?s=96&d=retro&r=g

Can you replace this?

Kind regards

Christian

**Comment by johngodley** [comment]
The retro flag only applies to users who have no avatar. That user has an avatar so it is shown.

Just a note that this isn't the place for support requests. We cannot replace avatars for you, and the user will need to manage this from their account.

**Comment by kresch23** [comment]
@johngodley TThank you for your reply. This is all clear to me, but this avatar is not a category of retro. A person is shown here, where should this error be placed? We do not assume that this is a picture of the user, because these are stored on our server. This is obviously a url to gravatar.com

**Comment by johngodley** [comment]
Yes, it is an image on Gravatar.

I am unsure what problem you are trying to describe. Can you explain more about what isn't working and what you expect to be happening?

**Comment by kresch23** [comment]
@johngodley  All our users have avatars that look like this:
![image](https://github.com/Automattic/gravatar/assets/53649191/13ccbea1-cbf4-4a86-9d19-3fd1dda26037)

The settings look like this:
![image](https://github.com/Automattic/gravatar/assets/53649191/d027eaf2-8b78-4f9f-9e57-597a4e6e8e6e)

From my point of view, this gravatar does not match our settings. Why does this user get a human?

**Comment by johngodley** [comment]
Sure, but as I mentioned above, that is not how Gravatar works. The style you pick is for people who do not have their own custom avatar. People who have an avatar will always show that avatar, and the setting is ignored.

**Comment by johngodley** [comment]
I don't know what it says in the settings there, but in English it looks like this:

![image](https://github.com/Automattic/gravatar/assets/1277682/6315ddea-394b-4cff-945e-67ca1c79950f)

That user has a custom avatar and that is the one that will be shown.

**Comment by kresch23** [comment]
@johngodley I don't think we understand each other. What you write is perfectly clear to me.

So you want to tell me that this avatar is one of the user's own?
https://secure.gravatar.com/avatar/667992afa821dd5b31def027c949aee1?s=96&d=retro&r=g

If not, is it an avatar that fits the "retro" style?

If not, this avatar is wrong in the "Retro" section, I just want to report this error/issue.

**Comment by kresch23** [comment]
@johngodley If this is a user image, how does it get to the URL gravatar.com?

**Comment by johngodley** [comment]
> So you want to tell me that this avatar is one of the user's own?

Yes, the user has uploaded this image.

> If not, this avatar is wrong in the "Retro" section, I just want to report this error/issue.

It is not wrong and is not an issue.

> If this is a user image, how does it get to the URL gravatar.com?

I don't know what you mean by this. The URL you have is a Gravatar URL.

**Comment by johngodley** [comment]
> If this is a user image, how does it get to the URL gravatar.com?

If by this you mean how does a user upload their photo then they do it at https://gravatar.com

**Comment by kresch23** [comment]
@johngodley Ok, thank you very much, then I really misunderstood. I thought you meant by "Yes, it's a picture on Gravatar" that this is a picture from Gravatar itself.

I will therefore read up on how it is possible for Gravatar to know our customers in order to assign the avatars correctly.
Thank you and sorry for the misunderstanding.
