### ISSUE TITLE
Request to add Vietnamese translation for Gravata

### ISSUE THREAD

**Issue by nguyenquanghoang** [Automattic/gravatar#63]
# Feature Request
Vietnamese translation for Gravata

## Description / Use Case
Many of our friends in Vietnam do not have access to Gravata in Vietnamese so they do not know how to create representative Avatars to comment on articles or to appear on other platforms.

## Proposed Solution
There needs to be a native language that makes Gravata faster and easier for all users to understand.

## Alternatives

I have now worked hard to complete 100% of the Vietnamese translation for Gravata here: https://translate.wordpress.com/projects/gravatar/vi/default/ Hope to be included in Gravata soon

**Comment by johngodley** [comment]
Once the translations have been approved they will be picked up in our weekly language update and appear on the site. I'll close this issue for now, and a big thanks for helping with the translations.

**Comment by nguyenquanghoang** [comment]
I think it will take another year for the Vietnamese translation for Gravata to be approved. 😂

**Comment by jom** [comment]
@nguyenquanghoang You've been made a validator for Gravatar's Vietnamese translations. You should be able to accept your translations now.  Thank you again for your contributions!

**Comment by nguyenquanghoang** [comment]
@jom Thank you so much, I really love Gravatar so I spent a lot of time translating just want more vietnamese beginners like me can know and use it 🙏

**Comment by nguyenquanghoang** [comment]
@jom The new homepage currently has new Strings that have not been updated to support Vietnamese translation.

**Comment by jom** [comment]
@nguyenquanghoang We update strings on translate.wordpress.com weekly. The new homepage just came out so should hopefully be up in the next day or two. We pull the translated strings from translate.wordpress.com at the same time so your translations should show up at the same time.

**Comment by nguyenquanghoang** [comment]
Yes, Thanks for explaining clearly.
