### ISSUE TITLE
Error displaying Vietnamese on Gravata

### ISSUE THREAD

**Issue by nguyenquanghoang** [Automattic/gravatar#75]
# Bug Report

I have now completed all Vietnamese translations 100%, but when checking there are still some positions that are not displayed, as shown in the image below

## Expected Behavior

This is an issue with receiving incorrect text domains, which needs to be fixed to display the translated String

## Repro Steps / Code Example

![1-Error displaying Vietnamese on Gravata](https://github.com/user-attachments/assets/bdac3b87-615f-4bfd-a75a-00887fa12c4b)
---
![2-Error displaying Vietnamese on Gravata](https://github.com/user-attachments/assets/58665071-b4f8-4bc0-84fa-f47ba1acd1a9)
---
![3-Error displaying Vietnamese on Gravata](https://github.com/user-attachments/assets/0ecc8004-2ea4-4f4d-bbd7-076da8a31919)
---
![4-Error displaying Vietnamese on Gravata](https://github.com/user-attachments/assets/fedd5d0e-ac87-44f7-9c9d-9370e5b579b0)

## Your Environment

- When logging into a Gravatar account on a desktop browser, Windows

## Additional Information

In addition: When accessing the Gravatar homepage https://gravatar.com/ on a mobile browser, Strings with html code like <span class="g-no-orphan">and verified links.</span> will be displayed smaller than the normal text, causing inconsistent display
(Note: This is not only the case with Vietnamese, but all languages ​​have this error.)

![Screenshot_20240908_082944_Edge](https://github.com/user-attachments/assets/0372f41e-7804-4ebb-b4ad-30795a5dbf5b)

- **Operating System / Browser:** Android / Chrome, Edge

**Comment by johngodley** [comment]
Again thank you for the translations.

We continue to make changes to text, and this may mean that some translations no longer match. We send all current text for translation every Friday, and any updates will then be incorporated the following week. It is likely that the phrases you mentioned will be included in this process soon, and I don't see any other problems with them otherwise.

The home page display seems to be as expected

**Comment by johngodley** [comment]
The translations have been updated and the above places are now showing the latest text. I'll mark this as closed!
