### ISSUE TITLE
I want to see Numerology as an Interest we can add to our Gravatar profiles. Astrology is the closest thing for now and it just won't do... 😞

### ISSUE THREAD

**Issue by mustafacco7** [Automattic/gravatar#87]
I want to see Numerology as an Interest we can add to our Gravatar profiles. Astrology is the closest thing for now and it just won't do... 😞 

This thread can also serve as a means for other uses to request Interests to add, so let the Gravatar team know what Interests you want added below.

_Originally posted by @juliusthejules in https://github.com/Automattic/gravatar/discussions/76_

**Comment by mustafacco7** [comment]
@mustafacco7

**Comment by wellyshen** [comment]
@mustafacco7 You can do it by typing "Numerology" and then pressing the "Enter" button as below:

https://github.com/user-attachments/assets/3de55db2-6800-4f84-92c6-559828d78565

**Comment by johngodley** [comment]
Closing this as complete.
