### ISSUE TITLE
The Verified Account System doesn't work correctly for Mastodon

### ISSUE THREAD

**Issue by schtobia** [Automattic/gravatar#9]
# Bug Report

## Description / Observed Behavior

I want to link [my Mastodon account](https://augsburg.social/@schtobia) to [my Gravatar account](https://gravatar.com/schtobia). On Gravatar's side, the function fails with the error message:
> We could not find a rel="me" back link to your Gravatar profile on the provided profile page.

![Screenshot 2024-06-21 083125](https://github.com/Automattic/gravatar/assets/4847926/b163010b-898d-4581-bb98-e78a8c70e392)

Additionally, the browser console drops the following message (full version on https://pastebin.com/57tGMrjc):
> POST
https://api.gravatar.com/v2/users/me/verify-rel-me?_locale=&source=web-app-editor
[HTTP/3 404 Not Found 1428ms]

## Expected Behavior

The link should be successfully created.

## Repro Steps / Code Example

See above.

## Your Environment

- Component/Service Name and Version: Gravatar Online Service
- Platform: Web
- Operating System / Browser: Both Firefox 115.12.0esr and Edge 126.0.2592.61

## Additional Information

Any other information about the problem here.

**Comment by johngodley** [comment]
Thanks, we'll look into this. You might want to delete the pastebin as it contains your authentication cookie.

**Comment by johngodley** [comment]
Can you copy/paste the full code here?

**Comment by schtobia** [comment]
Thanks, I've redacted the pastebin.

**Comment by johngodley** [comment]
@schtobia do you still have this problem?

**Comment by schtobia** [comment]
No, it seems to work now. Thanks for your work!
